### ISSUE TITLE
Support for random free ports for the mock

### ISSUE THREAD

**Issue by vinogradoff** [pact-foundation/pact-net#124]
Using .NET Pact Framework, is there any feature for choosing arbitrary free port for the mocks, built-in in the framework?

The reason is, that when some CI Jobs running in parallel for different services, ports collision is possible when the ports are hard-coded.

**Comment by neilcampbell** [comment]
@vinogradoff No unfortunately not. Because the port is passed into Pact, you have full control of finding a free port using something like this https://stackoverflow.com/questions/138043/find-the-next-tcp-port-in-net.

I had thought about building this into Pact, however it would have to work cross platform and I think it makes things more flexible to just recommend the test code decide which port to use before calling pact.
