### ISSUE TITLE
How to implement customize output for pact?

### ISSUE THREAD

**Issue by KenWang007** [pact-foundation/pact-net#129]
Hi Brother,

How to implement customize output for PactVerifierConfig , currently i use NUnit test framework in out project , and i want to output the pact test result in unit test window, but it didn't work , can you give some demo code to handle it , thanks .

currently code as bellow:

`

            const string serviceUri = "http://localhost:51502";

            var config = new PactVerifierConfig
            {
                Outputters = new List<IOutput>
                                  {
                                      new ConsoleOutput()
                                  }
            };

            IPactVerifier pactVerifier = new PactVerifier(config);
            pactVerifier
                .ServiceProvider("Event API", serviceUri)
                .HonoursPactWith("Event API Consumer")
                .PactUri("userclient-userservice.json")
                .Verify();
        }`

ConsoleOutput implementation 

` public class ConsoleOutput: IOutput
    {
        public void WriteLine(string line)
        {
            Console.WriteLine(line);
        }
    }`

when i run the test , it will throw the exception : 
`PactNet.PactFailureException : Pact verification failed. See output for details. 
If the output is empty please provide a custom config.Outputters (IOutput) for your test framework, as we couldn't write to the console.`

**Comment by neilcampbell** [comment]
Hi @KenWang007 
We implement and register a console outputter automatically, so there should be no need to do this, however if you are trying to implement a custom one, this is the correct way.

That error message is not actually asking you to implement a custom Outputter, it is saying that there is a Pact verification failure (something to do with your test) and you should check the console output to find the reason for the failure.

Maybe we should tweak the message to make that more clear. Does something like the below read better?

```
Pact verification failed. See output for details. Note: If the output is empty your test framework (e.g. xUnit) may be redirecting stdout, in which case you will need to provide a custom config.Outputters for your specific test framework in order to see the failure reason.
```

**Comment by andreimcristof** [comment]
@neilcampbell I have the same error and your reply to Ken is a bit confusing. Even if you modify the error as you suggest, it still will state that you need to provide custom outputters. However if you look closer in his sample, a custom outputter is precisely what he provided. He offered a list containing a ConsoleOutput instance. Should this not be what you mean, with providing custom Outputters? thx in advance.

**Comment by neilcampbell** [comment]
@andreimcristof A PactFailure exception is thrown when something fails to be performed correctly, in Ken's case the "Pact verification failed". The "Note" part of that message is just saying that if you see no details about why the failure occurred, you may need to register a custom outputter. Not registering a custom outputter will never be the cause of an exception. The "Note" part is always written, regardless of test framework and if you have registered one or not, as we don't know the runtime config at the time the exception is thrown. Does that make sense? Any suggestions to make this clearer?

**Comment by andreimcristof** [comment]
Thank you very much @neilcampbell for taking the time to answer and so quick even. Let*s break this down a bit:
1) let's make sure we speak about the same things:
The exception I receive on .Verify() is: 

> PactNet.PactFailureException: 'Pact verification failed. See output for details. 
If the output is empty please provide a custom config.Outputters (IOutput) for your test framework, as we couldn't write to the console.'

The error appears to be related to my PactVerifierConfig, which looks like this: 

`        private PactVerifier GetPactVerifier()
        {
            var config = new PactVerifierConfig
            {
                Outputters = new List<IOutput> { new ConsoleOutput() },
                Verbose = true
            };

            return new PactVerifier(config);
        }`

--------------
The exception indicates that the debugger output might have further details. This is the actual output:

> Exception thrown: 'PactNet.PactFailureException' in PactNet.dll
An exception of type 'PactNet.PactFailureException' occurred in PactNet.dll but was not handled in user code
Pact verification failed. See output for details. 
If the output is empty please provide a custom config.Outputters (IOutput) for your test framework, as we couldn't write to the console.

-------------
Now, you answer as follows:

> A PactFailure exception is thrown when something fails to be performed correctly, in Ken's case the "Pact verification failed".
I agree with this, and this was my understanding as well. I would indeed expect that "Pact Verification failed" refers to the very common case when the desired pact was not honoured, which as a consequence would throw some PactFailureException. 


> The "Note" part of that message is just saying that if you see no details about why the failure occurred, you may need to register a custom outputter. 
My understanding of this part of your answer is, that the custom outputter was not registered. By "not registered", I understand that the Outputters property in the PactVerifierConfig was not initialized at all - this is where the exception gets confusing, because as you see in the code I wrote above, when I instantiate PactVerifierConfig, I make sure to also initialize the Outputters, to a new List containing the ConsoleOutput. In my understanding, this would be the registering mentioned in the exception. So, why do I get the excception when I already satisfy the prerequisite? 

> Not registering a custom outputter will never be the cause of an exception.
This new piece of information makes it even more intriguing - so, what I understand from this sentence is  that regardless of whether I initialized the Outputters property or not, it should never cause a PactFailureException. Which means, my PactFailureException has nothing to do with the Outputters at all. It might be that the IsHonoured check did not pass - that*s what I am interested in, why it did not pass. But to get that detailed information, I need to now allow the library to write to console - which it seems to complain that it can*t. But in my understanding, I already did all I should do, in order to allow it to write to console. 

And finally, to actually answer your question - you ask me, is there any room for improvement in the actual exception message? Well, as the message currently stands, it leads me to believe that the library is not satisfied with the way I initialized property Outputters in the PactVerifierConfig instantiation, and it seems to want me to do a better job at allowing console output. But I am at a loss of what more should I do, considering my code above. It seems that the library wants to give me more details as to why the honoured check did not pass, but it can*t for a technicality (my apparent failure to allow console output). 
My suggestion is, just put those details of the PactFailureException in the actual exception message, perhaps the Inner Exception - instead of seeking a way to output them to the console. Hope it helps.


Please let me know if my wall-of-text makes sense and if not, I can try to be even more specific.

**Comment by neilcampbell** [comment]
Thanks for the detailed reply.

The ConsoleOutput is registered by default, and works for most test frameworks. xUnit however redirects the stdout and therefore the default handling does not work. See https://stackoverflow.com/questions/7138935/xunit-net-does-not-capture-console-output. When using xunit you need to provide a custom outputter, not the included ConsoleOutput. If you search the readme or samples for "XUnitOutput", you can see an example of how this is done. That should hopefully get you the details about why the exception was actually thrown.

**Comment by andreimcristof** [comment]
Thank you very much @neilcampbell I did as you suggested and now I get the test output as expected.
