### ISSUE TITLE
Keep getting intermittent "Actual interactions do not match expected interactions for mock" errors

### ISSUE THREAD

**Issue by ardz** [pact-foundation/pact-net#136]
Hello,

I'm really struggling with this. The example consumer test I have created is as follows:

```
[TestMethod]
        public void CreatePerson_WhereNoPersonExists_ReturnThePerson()
        {
            MockProviderService.Given("The user wishes to create a new person")
                .UponReceiving("A POST request to create the person")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Post,
                    Path = "/api/Person/",
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Query = "",
                    Body =
                        new
                        {
                            forename = "John",
                            surname = "Doe",
                            dateOfBirth = "1988-11-02T00:00:00Z",
                            ethnicity = 0,
                            gender = 1,
                            language = 0,
                            email = "johndoe@bah.org.uk"
                        }
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 200,
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Body =
                        {
                            message = "Person created successfully."
                        }
                }); //NOTE: WillRespondWith call must come last as it will register the interaction
    }
```
Error as follows:

Message: TestCleanup method RegistrationService.Tests.ConsumerPactTests.RegistrationTestsConsumePerson.VerifyAndClearInteractions threw exception. PactNet.PactFailureException: PactNet.PactFailureException: Actual interactions do not match expected interactions for mock MockService.

Missing requests:
	POST /api/Person/

See C:/PactFiles/person_service_mock_service.log for details.

I've also noticed that I HAVE to include the Query = "" parameter or none of the tests will work at all.

I'm struggling with this, I don't understand what the problem is? The following works (with the Query = "" parameter):

```
        [TestMethod]
        public void GetPerson_WhenThePersonExists_ReturnThePerson()
        {
            MockProviderService.Given("There is a person")
                .UponReceiving("A GET request to retrieve the person")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Get,
                    Path = "/api/Person/",
                    Headers = new Dictionary<string, object>
                    {
                        {"Accept", "application/json"}
                    },
                    Query = ""
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 200,
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Body =
                        new //NOTE: Note the case sensitivity here, the body will be serialised as per the casing defined
                        {
                            id = "ffe0c68a-19d7-4f39-b595-af145bf6c578",
                            forename = "John",
                            surname = "Doe",
                            dateOfBirth = "1988-11-02T00:00:00Z",
                            ethnicity = 0,
                            gender = 1,
                            language = 0,
                            email = "johndoe@bah.org.uk"
                        }
                }); //NOTE: WillRespondWith call must come last as it will register the interaction

            ApiTestClient.Get("/api/Person/", HttpStatusCode.OK);
        }
```

**Comment by daveboyle1** [comment]
I may not be reading this right as I'm reading on a mobile, but is your setup setting up for a post, but the method you are testing is doing a http get? I'm looking at in particular, apitestclient.get<http://apitestclient.get>()





Sent from OPPO Mail
On Richard <notifications@github.com>, 19 Jan 2018 12:53 am wrote:

Hello,

I'm really struggling with this. The example consumer test I have created is as follows:

`[TestMethod]
public void CreatePerson_WhereNoPersonExists_ReturnTheLearner()
{
MockProviderService.Given("The user wishes to create a new person")
.UponReceiving("A POST request to create the person")
.With(new ProviderServiceRequest
{
Method = HttpVerb.Post,
Path = "/api/Person/",
Headers = new Dictionary<string, object>
{
{"Content-Type", "application/json; charset=utf-8"}
},
Query = "",
Body =
new
{
forename = "John",
surname = "Doe",
dateOfBirth = "1988-11-02T00:00:00Z",
ethnicity = 0,
gender = 1,
language = 0,
email = "johndoe@mail.org.uk<mailto:johndoe@mail.org.uk>"
}
})
.WillRespondWith(new ProviderServiceResponse
{
Status = 200,
Headers = new Dictionary<string, object>
{
{"Content-Type", "application/json; charset=utf-8"}
},
Body =
new //NOTE: Note the case sensitivity here, the body will be serialised as per the casing defined
{
message = "Person created successfully."
}
}); //NOTE: WillRespondWith call must come last as it will register the interaction

        // ApiTestClient.Get("/api/Person/", HttpStatusCode.OK);
    }`


The test won't run because it's complaining about missing interactions:

"Actual interactions do not match expected interactions for mock MockService.

Missing requests:
POST /api/Person/"

It's a .NET core 2.0 class library using the latest version of MSTest. I don't understand what the problem is. I've also noticed that the Query = "" parameter has to present in any service request I create no matter what, or the test again will fail completely with "missing interaction".

Can someone shed any light on what the issue is or what I'm doing wrong here?

**Comment by daveboyle1** [comment]
also, open up the log file that is mentioned usually in the errors. There is usually good info in there to see what the issue is., if you havnt done so already





Sent from OPPO Mail
On Richard <notifications@github.com>, 19 Jan 2018 12:53 am wrote:

Hello,

I'm really struggling with this. The example consumer test I have created is as follows:

`[TestMethod]
public void CreatePerson_WhereNoPersonExists_ReturnTheLearner()
{
MockProviderService.Given("The user wishes to create a new person")
.UponReceiving("A POST request to create the person")
.With(new ProviderServiceRequest
{
Method = HttpVerb.Post,
Path = "/api/Person/",
Headers = new Dictionary<string, object>
{
{"Content-Type", "application/json; charset=utf-8"}
},
Query = "",
Body =
new
{
forename = "John",
surname = "Doe",
dateOfBirth = "1988-11-02T00:00:00Z",
ethnicity = 0,
gender = 1,
language = 0,
email = "johndoe@mail.org.uk<mailto:johndoe@mail.org.uk>"
}
})
.WillRespondWith(new ProviderServiceResponse
{
Status = 200,
Headers = new Dictionary<string, object>
{
{"Content-Type", "application/json; charset=utf-8"}
},
Body =
new //NOTE: Note the case sensitivity here, the body will be serialised as per the casing defined
{
message = "Person created successfully."
}
}); //NOTE: WillRespondWith call must come last as it will register the interaction

        // ApiTestClient.Get("/api/Person/", HttpStatusCode.OK);
    }`


The test won't run because it's complaining about missing interactions:

"Actual interactions do not match expected interactions for mock MockService.

Missing requests:
POST /api/Person/"

It's a .NET core 2.0 class library using the latest version of MSTest. I don't understand what the problem is. I've also noticed that the Query = "" parameter has to present in any service request I create no matter what, or the test again will fail completely with "missing interaction".

Can someone shed any light on what the issue is or what I'm doing wrong here?

**Comment by daveboyle1** [comment]
can read better now on PC. Can you tell us what method you are testing in your POST test? e.g. ApiTestClient.somemethod()? Just like how in your GET test, you have used ApiTestClient.Get(). It seems like the code you are testing is not making a POST request, based on the error, 

Missing requests:
POST /api/Person/"

Also, if you can show us the output of the log file from 

C:/PactFiles/person_service_mock_service.log 

That should also help.

Cheers,

Dave

**Comment by ardz** [comment]
Hi Dave,

Sorry I will get back to you with more information soon been mad busy!

Regards

Rich

**Comment by ardz** [comment]
Hi Dave,

I've uploaded a sample project:

https://github.com/ardz/PactTesting

Trying to run the consumer test throws the following error:

`Test Name:	GetThing_WhenTheThingExists_ReturnTheThing
Test FullName:	ConsumerTests.Tests.GetThing_WhenTheThingExists_ReturnTheThing
Test Source:	E:\github\source\PactTesting\ConsumerTests\Tests.cs : line 43
Test Outcome:	Failed
Test Duration:	0:00:13.3514103

Result StackTrace:	
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, String requestUri)
   at ConsumerTests.ApiClient.MakeRequest(HttpMethod method, String endpoint, IReadOnlyList`1 headers) in E:\github\source\PactTesting\ConsumerTests\ApiClient.cs:line 30
   at ConsumerTests.Tests.GetThing_WhenTheThingExists_ReturnTheThing() in E:\github\source\PactTesting\ConsumerTests\Tests.cs:line 71

TestCleanup Stack Trace
   at PactNet.Mocks.MockHttpService.AdminHttpClient.SendAdminHttpRequest[T](HttpVerb method, String path, T requestContent, IDictionary`2 headers) in C:\projects\pact-net\PactNet\Mocks\MockHttpService\AdminHttpClient.cs:line 72
   at PactNet.Mocks.MockHttpService.MockProviderService.VerifyInteractions() in C:\projects\pact-net\PactNet\Mocks\MockHttpService\MockProviderService.cs:line 116
   at ConsumerTests.Tests.VerifyAndClearInteractions() in E:\github\source\PactTesting\ConsumerTests\Tests.cs:line 26
Result Message:	
Test method ConsumerTests.Tests.GetThing_WhenTheThingExists_ReturnTheThing threw exception: 
System.UriFormatException: Invalid URI: Invalid port specified.
TestCleanup method ConsumerTests.Tests.VerifyAndClearInteractions threw exception. PactNet.PactFailureException: PactNet.PactFailureException: Actual interactions do not match expected interactions for mock MockService.

Missing requests:
	GET /api/values/

Unexpected requests:
	GET /api/values
	GET /api/values

See C:/PactFiles/provider_api_mock_service.log for details.
.
Result StandardOutput:	
[2018-01-31 16:58:18] INFO  WEBrick 1.3.1
[2018-01-31 16:58:18] INFO  ruby 2.2.2 (2015-04-13) [i386-mingw32]
[2018-01-31 16:58:18] INFO  WEBrick::HTTPServer#start: pid=8028 port=9222
[2018-01-31 16:58:18] INFO  WEBrick 1.3.1
[2018-01-31 16:58:18] INFO  ruby 2.2.2 (2015-04-13) [i386-mingw32]
[2018-01-31 16:58:18] INFO  WEBrick::HTTPServer#start: pid=8788 port=9222

`

**Comment by daveboyle1** [comment]
Ok great. I'll try to have a look today. From a quick browse of the error, it looks like your headers don't match between the expected request and the actual request. It looks like you are using postman in the browser. Anyway, I'll look at the project properly to see what's going on. Cheers.

**Comment by daveboyle1** [comment]
Hi @ardz,

I tried to push a branch to your repo but was getting 403 forbidden even after changing to ssh. anyway, i was able to get your tests running. i'll just paste the changes in here.

`   [TestMethod]
        public void GetThing_WhenTheThingExists_ReturnTheThing()
        {
            MockProviderService.Given("There is a thing")
                .UponReceiving("A GET request to retrieve the thing")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Get,
                    Path = **"/api/values",**  // removed the slash at the end
                    Headers = new Dictionary<string, object>
                    {
                        {"Accept", "application/json"}
                    },
                    **Query = ""**  // add query back in as it matched against null
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 200,
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Body =
                        new //NOTE: Note the case sensitivity here, the body will be serialised as per the casing defined
                        {
                            value1 = "value1",
                            value2 = "value2"
                        }
                }); //NOTE: WillRespondWith call must come last as it will register the interaction

            var response = ApiTestClient.MakeRequest(HttpMethod.Get, **"/api/values"**); // the url that was //here was not building a proper URL in the api client

            var content = ApiTestClient.HttpResponseToString(response);

            Assert.IsNotNull(content);
        }`

See the comments in the code.
 Also, you dont need to set your pact version in the constructor either. i didnt look much further than that. just wanted to get the test working. 

let me know if any questions

Cheers,

Dave

**Comment by neilcampbell** [comment]
Awesome stuff @daveboyle1, thanks heaps for looking into this!

**Comment by daveboyle1** [comment]
no worries @neilcampbell.

**Comment by ardz** [comment]
@neilcampbell @daveboyle1 

hi guys, thanks for looking at this! still having the same issue even with those changes you mentioned Dave (had already tried those changes above :/)

error:

TestCleanup method ConsumerTests.Tests.VerifyAndClearInteractions threw exception. PactNet.PactFailureException: PactNet.PactFailureException: Actual interactions do not match expected interactions for mock MockService.

Missing requests:
	GET /api/values

See C:/PactFiles/provider_api_mock_service.log for details.

Log file:

I, [2018-02-01T10:49:14.668734 #15532]  INFO -- : Registered expected interaction GET /api/values
D, [2018-02-01T10:49:14.669694 #15532] DEBUG -- : {
  "description": "A GET request to retrieve the thing",
  "providerState": "There is a thing",
  "request": {
    "method": "get",
    "path": "/api/values",
    "query": "",
    "headers": {
      "Accept": "application/json"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json; charset=utf-8"
    },
    "body": {
      "value1": "value1",
      "value2": "value2"
    }
  }
}
W, [2018-02-01T10:49:14.684772 #15532]  WARN -- : Verifying - actual interactions do not match expected interactions for example "". 
Missing requests:
	GET /api/values


W, [2018-02-01T10:49:14.684772 #15532]  WARN -- : Missing requests:
	GET /api/values


I, [2018-02-01T10:49:27.166361 #15532]  INFO -- : Cleared interactions for example ""

**Comment by ardz** [comment]
Ok, so if I run the test straight through with those changes it's fine...

I'm curious as to why I'm not able to run it through on debugging then hit the mock server and get the example values is that how it should behave (i.e. the screenshot?)

Cheers guys!
