### ISSUE TITLE
Path to the library base_administration_request_handler.rb too long

### ISSUE THREAD

**Issue by vikasillumina** [pact-foundation/pact-net#160]
Hi @neilcampbell @bethesque ,

Our team has been using Pactnet library very nicely for months now. However we are running into issue where some of the path of test projects is little longer (we are using mono repo containing all the microservices) and any project that is referring the Pactnet library fails to compile due to path length issue. Here is the info on the library file in question here:
`pact-win32\lib\vendor\ruby\2.2.0\gems\pact-mock_service-2.7.1\lib\pact\mock_service\request_handlers\base_administration_request_handler.rb.`

The error we get is:
`The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

Is there a way these library names can be shortened? :) I understand this is a ruby library and your team might not be able to control this, but if it can be shortened it will help. I am trying to convince people on my team too to find ways to shorten the paths too.

Thanks in advance.

Regards,
Vikas

**Comment by bethesque** [comment]
Can you do a search on the existing issues, as there have been some fixes suggested for this (enabling long paths in windows I believe).

It is a known issue, and the path length cannot be fixed with the current method of packaging the code. The long term solution is to move to a shared Rust library with FFI bindings. Another solution is to re-package the current code, which I've been working on, but am blocked because the author of the packaging library has been unable to help me with an issue. I need a *windows* ruby expert to help me.

**Comment by vikasillumina** [comment]
Thanks Beth this is helpful. I will close this issue.
