### ISSUE TITLE
Provided a strongnamed/signed version of PactNet

### ISSUE THREAD

**Issue by elangelo** [pact-foundation/pact-net#187]
A lot of opensource projects provide next to the 'unsigned' version at least the option to install a signed version.

**Comment by neilcampbell** [comment]
Hi @elangelo 
Creating an additional signed assembly package adds another level of complexity to the build process and we then need to manage the private key used for signing securely. On top of this PactNet is a testing library, so it should never be shipped in your actual app. Because of these reasons we have no intention to add signed versions of the assemblies.

**Comment by elangelo** [comment]
that is a workaround i didn't think about. We usually just sign all our assemblies but i can agree with not signing the test dll that is running our contract tests.
