### ISSUE TITLE
SSL connect error while using PactNet.Windows 

### ISSUE THREAD

**Issue by mayankdotnet** [pact-foundation/pact-net#258]
I am using PactNet.Windows package for Contract testing. Using this package I am able to Create consumer contract tests and publish the same to the broker which have a SSL implemented. But when I we are trying to verify the contract using contract broker url following error is being reported:

**SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed "/bin/Release/netcoreapp3.1/pact-win32/lib/ruby/lib/ruby/2.2.0/net/http.rb:923:in `connect'"**

I have tried using different versions of the library including the latest one for each version I tried I have always received same error.

I have tried verifying and publishing the pact through standalone tool: **https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.88.3**

Also I have added environment variable for **SSL_Cert_File** pointing towards the SSL certificate still getting same error every time.

**Comment by bethesque** [comment]
Because I don't have access to a Windows env, I've been unable to reproduce this issue. You can find some history on it here https://github.com/pact-foundation/pact-ruby-standalone/issues/30

I think the workaround was to put the SSL cert into the right place in the pact ruby standalone dir.

**Comment by thomas-girotto** [comment]
> I think the workaround was to put the SSL cert into the right place in the pact ruby standalone dir.

Well if you mean modifying pact-win32\lib\ruby\lib\ca-bundle.crt that would work but that's not really a solution as it couldn't be applied in a CI context where we restore each time the nuget package, and doing it on each dev's machine (and remembering that you should do it again each time you loose your nuget packages cache) is not really possible.

A better solution that worked for me is to set SSL_CERT_FILE environment variable with a path to my own ca-bundle.crt containing the needed certificates (don't forget to set the whole chain of certificates inside).

But with this solution we still need to set this environment variable on every machine that will run the test project (devs and CI), and have our custom ca-bundle.crt installed somewhere on those machines.

So i'd like to do a PR in which i would give the ruby process the SSL_CERT_FILE environment variable that could be set from dotnet config.
Something like:

```
pactVerifier
  .ServiceProvider("MyService", $"http://localhost:{address.Port}")
  .HonoursPactWith("MyClient")
  .PactUri(
    "https://uri/to/myclient-pact.json", 
    new PactUriOptions 
    { 
      SslCaFilePath = "PathToYourOwnCaBundle" <- proposition of new property
    })
  .Verify();
```
And then use this new config to add SSL_CERT_FILE environment variable to the ruby process the same way than [here](https://github.com/pact-foundation/pact-net/blob/40edbf5991328272f5a212f608d06b3cc96799ac/PactNet/Core/PactCoreHost.cs#L96):

That way, we could have our ca-bundle.crt in source control, and setup the path to this file at runtime, and don't need to setup anything neither on devs machine nor on CI machines.

Do you see any issue in doing so?

**Comment by bethesque** [comment]
Sounds good. Give it a crack.

**Comment by bethesque** [comment]
I haven't been able to fix the SSL_CERT_FILE env var issue for windows because I don't have a windows environment. I'm sure it could be debugged and fixed easily by someone who was familiar with windows, but nobody who actually has the problem has been been willing to spend the time on it.

**Comment by bethesque** [comment]
Sorry, I should make it clear - your proposal to expose the cert file setting in the .net code sounds good, but there is still the underlying issue that setting the env var *does not work* and I don't know why.

**Comment by thomas-girotto** [comment]
> but there is still the underlying issue that setting the env var _does not work_ and I don't know why.

Setting SSL_CERT_FILE actually works, maybe some people thought it didn't because they only set the last certificate of the chain inside their ca.crt file instead of setting the whole chain (that was my mistake at first). But given the custom ca.crt is set up properly, pointing SSL_CERT_FILE to that file works.

> your proposal to expose the cert file setting in the .net code sounds good

So OK, i'll propose a PR soon!

**Comment by thomas-girotto** [comment]
> Setting SSL_CERT_FILE actually works

My mistake, what actually works is to set ORIG_SSL_CERT_FILE (i got confused with all the different tries i've made before making it work)

**Comment by bethesque** [comment]
Hm. The ORIG_SSL_CERT_FILE is supposed to contain SSL_CERT_FILE, because it overwrites SSL_CERT_FILE with the default internal one at some stage, and then sets it back again at the end. Would you mind doing a little digging? I'm sure it's a straightforward fix if you have a Windows env to run it on!

**Comment by thomas-girotto** [comment]
Ok so what happens is:

1. dotnet starts ruby process using this [config file](https://github.com/pact-foundation/pact-net/blob/40edbf5991328272f5a212f608d06b3cc96799ac/Build/windows/config.json#L9) to pass environment variables to ruby process [here ](https://github.com/pact-foundation/pact-net/blob/40edbf5991328272f5a212f608d06b3cc96799ac/PactNet/Core/PactCoreHost.cs#L83). So at this point, if SSL_CERT_FILE has been set in the system it is overriden with the path to the default bundle
2. The ruby script to execute is [this one](https://github.com/pact-foundation/pact-ruby-standalone/blob/f6e44fa0173e73ba2b9d4c44311090e524c5656a/packaging/pact-provider-verifier.rb#L10) and we can override the previous SSL_CERT_FILE with ORIG_SSL_CERT_FILE if it exists

So all in all, it doesn't sound like a bug to me but more an expected behavior, that should maybe more clearly documented in the readme.

We could change this behavior by not giving the SSL_CERT_FILE from config.json if it is already set in the system, but as this environment variable is widely used for a lot of different programs, that could break a lot of users...

So the best way to go i guess is to be able to set a property SslCaFilePath like i proposed, and give SSL_CERT_FILE to ruby process with this value instead of the one coming from config.json if it set.
