### ISSUE TITLE
Add documentation on how to use Message pact in .net core for Event driven services. 

### ISSUE THREAD

**Issue by shobhitkasliwal-onbe** [pact-foundation/pact-net#344]
Hello - 
It would be helpful if we add documentation on how to use message pact in .net.  I am not able to find much documentation on how to use PactNet library for message pact for event driven services.

**Comment by mefellows** [comment]
That's because the current version does not yet support message Pact!

The new [4.x.x branch](https://github.com/pact-foundation/pact-net/blob/feature/4.0.0) will, and there is a [sample project](https://github.com/pact-foundation/pact-net/blob/feature/4.0.0/samples/EventImporter/Consumer.Tests/EventImporterTests.cs) in there you could use as a guide.

**Comment by shobhitkasliwal-onbe** [comment]
Thank you @mefellows  for the response. Do you know when the new version will be released ?

**Comment by CeeJayCee** [comment]
I would like to +1 this request.

I am trying to use [4.0.0-beta.1](https://www.nuget.org/packages/PactNet/4.0.0-beta.1) and follow the samples provided. 

It's not clear how to use this with, for example, a Kafka<->Kafka message producer/consumer. The samples reference PactNet.AspNetCore.Messaging but this is not available via NuGet.

**Comment by adamrodger** [comment]
That package is removed as part of #369, then I'll write docs once the API is stable

**Comment by mefellows** [comment]
Wow, the beta is out two minutes and you're being hassled for docs - people are keen! 🥳
