### ISSUE TITLE
Add Support for Custom Headers During Verification

### ISSUE THREAD

**Issue by fabio-andre-rodrigues** [pact-foundation/pact-net#373]
## Context
Given that the rust implementation for handling custom headers, this Feature request is to create the necessary bridge to pass the values from provider side to the rust implementation, so that the CustomHeaders mechanism works like v3.x.x

## Rust implementation
https://github.com/pact-foundation/pact-reference/issues/182

**Comment by adamrodger** [comment]
Assuming the linked issue in `pact-reference` is implmented, PactNet could be modified to add a new `WithCustomHeader` method to https://github.com/pact-foundation/pact-net/blob/master/src/PactNet.Abstractions/Verifier/IPactVerifierSource.cs

This would then need plumbing through to the FFI call so that the Rust side can add the custom headers to the request

**Comment by fabio-andre-rodrigues** [comment]
Exactly

A segunda, 21/02/2022, 12:51, Adam Rodger ***@***.***>
escreveu:

**Comment by fabio-andre-rodrigues** [comment]
Ok, pact-rust has ffi for custom headers

**Comment by uglyog** [comment]
I still need to release the Pact-Rust FFI lib, which I'm hoping to do shortly.

**Comment by adamrodger** [comment]
Available in FFI 0.2.3
