### ISSUE TITLE
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'PactNet.RequestBuilder.WillRespond()' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by gyuvaraj10** [pact-foundation/pact-net#384]
with 4.0.0-beta.x(1,2,3)
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'PactNet.RequestBuilder.WillRespond()' is inaccessible due to its protection level

_pactBuilder
                .UponReceiving("A request to patch the item by id e69a14fd")
                .Given("An item With xyz state State is available in Database", new Dictionary<string, string>
                {
                    { "itemId" , "e69a14fd" },
                    {"itemData", json }
                })
                .WithRequest(HttpMethod.Patch, "/api/v1/items/e69a14fd")
                .WithHeader("Content-Type", "application/json-patch+json")
                .WithJsonBody(ToDynamicResponse<Item>(data))
                .WillRespond()
                .WithStatus(HttpStatusCode.OK);

**Comment by adamrodger** [comment]
Could you give some more feedback about your test project? For example which Pact Specification version and .Net version you were using?

Preferably a sample project that recreates the problem would be best, because the PactNet tests pass so this must be a framework/specification/OS combination or something that the tests don't cover.

**Comment by adamrodger** [comment]
Closing as stale after the requested feedback wasn't received.
