### ISSUE TITLE
WARN: Ignoring unsupported matching rules in "PactNet.OSX" Version="3.0.2"

### ISSUE THREAD

**Issue by tl-madhulika-mitra** [pact-foundation/pact-net#388]
Hi.

My consumer is JVM pact version 4.1.7 and my provider is DotNet pact version 3.0.2.
The matchers and generators made from consumer is being ignored at provider layer. Does the provider need to upgrade to 4.0.0-beta.3 to get this supported?

**Comment by adamrodger** [comment]
Generators are a feature of Pact spec V3 and above, whereas PactNet v3.x only supports up to Pact spec V2.

**Comment by YOU54F** [comment]
Hi @tl-madhulika-mitra, you are probably best asking more general questions about compatibility in slack.pact.io rather than GitHub issues, unless there is a particular issue with the tool.

For more general feature requests, we currently have our https://pact.canny.io/ roadmap, where you can vote for a particular item.

This helps save the maintainers headspace for future features / bug fixes etc 👍🏾
