### ISSUE TITLE
chore: Upgrade FFI to version 0.3.18

### ISSUE THREAD

**Issue by leonasa** [pact-foundation/pact-net#434]

**Comment by mefellows** [comment]
The latest version is 0.3.18, so should we go straight to that?

**Comment by leonasa** [comment]
Do you prefer to increment it one by one? It would make sense, actually!

**Comment by mefellows** [comment]
I'll leave that for the maintainer (Adam) to decide. But I think a jump straight to the latest is fine, as there shouldn't be breaking changes in it (semver and all that).

**Comment by adamrodger** [comment]
Unfortunately the semver is still on 0.x and so breaking changes can happen (and have previously). For example, one FFI upgrade broke logging so we had to skip a few versions until it was fixed.

If there's a reason to upgrade then we do that prior to whatever that unlocks though (e.g. if there's a new feature to add but that needs a new FFI version then that prompts the change).

We don't upgrade just in general at the moment though unless it provides a required fix or unlocks a new feature, just because it can and does break things.
