### ISSUE TITLE
Is there anyway to configure RedirectHandling in Pact-Net similar to Pact JVM

### ISSUE THREAD

**Issue by ImNag** [pact-foundation/pact-net#441]
I see there is a configuration to enable/ disable RedirectHandling `pact.verifier.enableRedirectHandling` for Provider Verification in Pact JVM. Wondering, if there is similar configuration is Pact Net. Currently, i observe Pact Net verifier tries to handle the redirection when there is 301 status. Wondering, if we can disable such behaviour.

Using PactNet Version="4.3.0"

From Pact JVM docs:
<img width="862" alt="Screenshot 2023-01-27 at 17 44 03" src="https://user-images.githubusercontent.com/26590400/215067536-14e9dc5f-0e03-4a3e-9f19-c1c2f0a831fa.png">

**Comment by mmilind** [comment]
I am facing a similar problem with my application

**Comment by TimothyJones** [comment]
Not an answer to this question, but in most cases you probably should write the contract with what you're expecting at the end of the 3XX instead - as that's what your application will eventually receive. It's more appropriate for that to be in the contract (if you can write it that way).

**Comment by ImNag** [comment]
@TimothyJones Yeah Agree. Initially I did write pact test to expect 3xx as status code with Pact Net Provider Spec V2 and was able to assert it. After migrating to Spec V3, i feel provider is trying to handle redirect also before verification. So, was not able assert for 3xx status code. Wondering, if there is a configuration on provider, which could disable this behaviour.

Also, if we were thinking along the lines to assert the things that application will receive eventually, is there a way to assert for URL once response is received. Maybe thinking to assert for final url after re-direction.

**Comment by adamrodger** [comment]
Currently there's no way to configure this, no.

**Comment by TimothyJones** [comment]
Sorry, I think I wasn’t clear above- I’m advocating _not_ putting the redirect in the contract- since the behaviour you want a contract for (usually) isn’t “redirect the client”, it’s “get a response in the following format”.

Whether or not there is a redirect on the way to that response is an implementation detail.

The same argument applies to the URL- probably the specific URL is an implementation detail, and not something the client is relying on.

Remember that the contract is for recording the behaviour the client relies on, not the behaviour of the provider. Unless the client needs the redirect as part of its logic (which is possible, but unlikely) it’s best to have it invisible from the perspective of the consumer test.

**Comment by adamrodger** [comment]
Closing as there is no plan to support this (and it's not possible in the current FFI).
