### ISSUE TITLE
Provider tests - .NET6 Minimal API support

### ISSUE THREAD

**Issue by arnoldsi-payo** [pact-foundation/pact-net#444]
Hi,
As you probably know that from .NET 6, all the configurations are at the top level.
I've tried to find a clean solution to run the app for provider testing. 
One of the options is to move the new code to the static main class and run it or revert it to the old way.

I would like to know if can suggest ideas to overcome this issue
Thank you

**Comment by arnoldsi-payo** [comment]
@adamrodger thank you for your response. The issue that will probably occur is that moving forward.NET versions, all startups will be using top-level code without a startup file. Pact Requires a running server and does not support a mocking server (such as TestServer or WebApplicationFactory).
With that said, this will be a significant issue for PactNet to handle and might reduce the usage of this library.

**Comment by aleroca96** [comment]
@arnoldsi-payo  completely agree, the library is great and I see the use of contract tests being adapted more and more. However, because of this lack of .Net6 minimal API support I will have to find an alternative to it.

Great job on the library and hopefully this issue is overcome as more users ask for it! :)

**Comment by adamrodger** [comment]
A quick Google will lead you to the Microsoft documentation where they show you how to integration test a Minimal API:

https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests

Or this InfoWorld article:

https://www.infoworld.com/article/3668174/how-to-test-minimal-apis-in-asp-net-core-6.html

Among many others.

You also have the option of not using Minimal APIs and keeping the Startup class. I personally prefer that approach. There are other options as well.

Like I say, it's out of scope for PactNet to tell you what the best way to host or structure your code is.

**Comment by mefellows** [comment]
> @adamrodger thank you for your response. The issue that will probably occur is that moving forward.NET versions, all startups will be using top-level code without a startup file. Pact Requires a running server and does not support a mocking server (such as TestServer or WebApplicationFactory).
With that said, this will be a significant issue for PactNet to handle and might reduce the usage of this library.

Thanks for sharing. One of the reasons for this is that our Pact client libraries use a shared core, which is responsible for much of the communication to/from the tests themselves. This is a shared library written in Rust that exports a C interface - so having a native .NET experience in the way that (I think) you need, is not likely to be possible.

**Comment by adamrodger** [comment]
@mefellows it's a slightly different issue to that. I think what you're referring to is the lack of support for TestServer/WebApplicationFactory, and on that you're absolutely correct. That can't be used because the cure Rust library wouldn't be able to access the in-memory host.

What the issue (and the other duplicate issue) are referring to is a new .Net feature called Minimal APIs.

This feature does a lot of magic for you to do with the hosting, but unfortunately some test libraries need to hook into that hosting to work properly. One such library is PactNet, but so is WebApplicationFactory.

The official MS docs show how to enable hooking into that if you need to from a test project, and there are other techniques as well, so this is out of scope for PactNet itself. It's a general problem with testing Minimal API, and there are official solutions to it.

**Comment by k30v1n** [comment]
It would be nice to build an example of implementing a provider when the app don't have the Startup file, which is the new standard for the framework ad it is going to be followed for future versions as well.

I agree that this is a friction of adopting this library. Even because all the integration tests I found (including the ones pointed out on this issue comments) use the in memory host with `WebApplicationFactory<Program>`.

**Comment by adamrodger** [comment]
There are lots of different ways to host your application on a real HTTP port, and that's out of scope for PactNet to mandate any one approach.

A quick Google shows a number of different ways, for example see this repo (particularly the HttpFixture):

https://github.com/martincostello/dotnet-minimal-api-integration-testing

You just start a normal Host instead of using the TestHost.

It's no different than having to start your application on a real HTTP port when using an integration testing framework like Cypress or Playwright.
